-- Sheet for Rondo Alla Turca by Wolfgang Amadeus Mozart

shared.stop = true -- stops the player at any time if true
-- CONFIG:
shared.ftime = 9*60 + 25 -- time in seconds for the song to finish (extended by |)
shared.delay = nil -- delay overides the ftime
shared.tempo = nil -- tempo overides the delay

shared.scr = [WYto] J - h h - [Eyig] D d - P P [Ytos] - D J h [Ewyi] - h H  - H J [WYt] - g h g - D [wry] - D [ryid] s - [etup] n [fv] C [fz] k h  G f - o [etuop] a s h - d [tuoa] - s - [eyih] a s [ruod] h [tipk] - l [Ory] h [etuop] a s h  - d [tuoa] - s - [eyih] a s [ruod] h [tipadgk] [tipadgk] [ryuoh] d a o [6ejlxb] e [etuhkzv] - [6edgjz] [5wadgk] [5w]  [wtusfhl] [5w] [qadgk] q [qeyhkzv] - [qjlxb] [Qkzcn] Q [Oyulxvm] Q [6ejlxb] e [etuhkzv] - [6edgjz] [5wadgk] [5w] [wtusfhl] [5w] [qadgk] q [eyhkzv]  - [qjlxb] [Qzcn] k Q [HVkx] [Oyu] [Hfkx] Q [6ejlxb] e [etuhkzv] - [6edgjz] [5wadgk] [5w] [wtusfhl] [5w] [qadgk] q [qeyhkzv] [qjlxb] [Qkzcn] Q [Oyulxvm] Q  [6ejlxb] e [tuhkzv] - [6edgjz] [5wadgk] [5w] [wtusfhl] [5w] [DGZqj] q [Gqeydjz] - [Gqdjz] [QGdjz] [Qfhx] [QIGCtj] |  --- [6ep] - e [6j] e [%Wh] - W [%f] W [5wd] - [ws] 5 [wa] Q l Q - Q q  - q k [qh] 0 - 0 - 0 [6d] - [6h] - [6g] [6f] - [6a] - [6p] [6ep] - e [6j] e [%Wh]  - W [%f] W [5wd] - [ws] 5 [wa] Q s Q - Q q - q - q 0 u 0 u [0o] [6a] - p - [6a] - [qp] [eta] - [qs] -- [5wf] - [wd] - [ryh] - [5wd] - w - [rys]  [wd] [6ef] - [ed] [ed] [tu] [es] [5wo] - w - [ry] w [qp] - [qa] - [ets] - [5wa] [5w] [ryp]  w [Ory] r [6ep] - [6es] - [6ef] - [8ts] - [8tf] - [8tp] - [ql] -- k q [qh] q  q [5w] [%W] [6e] [6elvm] -- [etukxn] - [6ehkzv] [8tdhz] [tu] [tusfhl] [tu] [8t] [7r] [qs] d [qf] [eth] q  [qf] [5wd] [5w] [5ws] [ryd] [5wj] [6esfh] t e [%W] t W [5wlxvm] t w Q t w [qlxvm] - - [qetkzvn] - [qhkzv] [qhkzv] [et] q [et] [5wjb] [6elvm] -- [etukxn] - [6elxvm] [8tdhz] [tu] [tusfhl] [tu] [8t] [7r]  [qf] p [qf] [etd] q [qd] f [5wh] [5w] [5wf] [ryd] [5ws] [6es] t e [%W] t [Wf] [5wd] t [ws] Q  t w [qlxvm] -- [qetkzvn] - [qhkzv] q [et] q [et] [5w] [6elvm] -- [etukxn] - [6elxvm] [8tdhz] [tu]  [tusfhl] [tu] [8t] [7r] [qs] d [qf] [eth] q [qf] [5wd] [5w] [5ws] [ryd] [5wj] [6eh] t e [%W] t  W [5wl] t w Q t w [qlxvm] -- [qetkzvn] - [qhkzv] q [et] q [et] [5whkzv] [6elvm] - - [etukxn] - [6elxvm] [8tdhz] [tu] [tusfhl] [tu] [8t] [7r] [qs] d [qf] [eth] q [qf] [5wd] [5w] [5ws] [ryd] [5ws] [6es]  0 [6e] 0 [6e] 0 [8t] w [8t] w [8t] w [qis] d f h o [if] [wod] - [ys]  [rd] [ts] [6ef] - 6 6 [et] e [8th] [8t] [uo] t [8t] [8t] | -
